const $=s=>document.querySelector(s);let timer=null,elapsed=0,events=0,seed=42771,viewMode='overview';const eventList=$('#eventList'),competitive=CyberRumbleCompetition.runCompetitiveMatch(seed,[{A:'fast',B:'guarded'},{A:'guarded',B:'fast'},{A:'fast',B:'guarded'}]),match=competitive.replay,matchScore=competitive.score;let current=0,scoreA=0,scoreB=0;
function hash(){return CyberRumbleEngine.fnv(JSON.stringify({seed,events,round:match.events[Math.max(0,current-1)]?.round||1})).slice(0,4)+'·'+match.digest.slice(0,4)}
function eventRow(event,time){const row=document.createElement('div');row.className='event';row.innerHTML=`<time>${String((time/1000).toFixed(1)).padStart(5,'0')}</time><span class="${event.cls}"><b>${event.kind} / ${event.actor}</b><br>${event.text}</span>`;return row}
function updateLink(event){if(viewMode==='overview'){$('#activeLink').setAttribute('d','M320 80 L170 165');return}const focus=event?.kind==='ACTION'?event:match.events.slice(0,current).reverse().find(e=>e.kind==='ACTION');const actor=focus?.actor==='B'?'B':'A';$('#activeLink').setAttribute('d',actor==='B'?'M320 80 L470 165':'M320 80 L170 165')}
function narrate(event){if(!event){$('#roundLabel').textContent='ROUND 01 / OPENING READ';$('#callout').textContent='Two policies enter the same closed world. The first verified interrupt wins the round.';return}$('#roundLabel').textContent=`ROUND ${String(event.round).padStart(2,'0')} / ${event.tick<3?'OPENING READ':event.tick<7?'COUNTERPLAY':'INTERRUPT WINDOW'}`;$('#callout').textContent=event.kind==='SYSTEM'?`Round ${event.round} is verified from the decision trace: ${event.text}.`:event.tick<3?'Both policies map the same target without privileged context.':event.tick<7?`${event.actor} commits a legal move; the opposing path remains observable.`:`${event.actor} is inside the decisive interrupt window. Only the verifier can call the round.`}
function updateScore(target){scoreA=match.events.slice(0,target).filter(e=>e.tick===8&&match.winners[e.round-1]==='A').length;scoreB=match.events.slice(0,target).filter(e=>e.tick===8&&match.winners[e.round-1]==='B').length;$('#scoreA').textContent=scoreA;$('#scoreB').textContent=scoreB}
function setFrame(target){clearInterval(timer);timer=null;target=Math.max(0,Math.min(match.events.length,target));current=target;events=target;elapsed=target*450;eventList.innerHTML=target?'':'<div class="empty-state">Press RUN MATCH to emit<br />deterministic telemetry.</div>';for(let i=0;i<target;i++)eventList.prepend(eventRow(match.events[i],i*450));updateScore(target);const last=match.events[target-1];narrate(last);updateLink(last);$('#eventCount').textContent=String(target).padStart(3,'0');$('#clock').textContent=`00:${(elapsed/1000).toFixed(1).padStart(4,'0')}`;$('#progressBar').style.width=(target/match.events.length*100)+'%';$('#stateHash').textContent=hash();$('#scrubber').value=target;$('#scrubLabel').textContent=target?`FRAME ${String(target).padStart(2,'0')} / 24`:'LIVE';$('#round').textContent=String(last?(last.tick===8?Math.min(3,last.round+1):last.round):1).padStart(2,'0');if(target===0){$('#phase').textContent='READY';$('#runBtn').textContent='▶ RUN MATCH'}else if(target<match.events.length){$('#phase').textContent=`REPLAY / FRAME ${String(target).padStart(2,'0')}`;$('#runBtn').textContent='▶ RESUME FROM FRAME'}else{finish()}}
function pushEvent(event){events++;current=events;if(events===1)eventList.innerHTML='';eventList.prepend(eventRow(event,elapsed));$('#eventCount').textContent=String(events).padStart(3,'0');$('#scrubber').value=events;$('#scrubLabel').textContent=`FRAME ${String(events).padStart(2,'0')} / 24`;$('#stateHash').textContent=hash();narrate(event);updateLink(event);if(event.tick===8){updateScore(events);if(event.round<3){$('#round').textContent=String(event.round+1).padStart(2,'0');$('#phase').textContent='NEXT ROUND'}else $('#phase').textContent='MATCH POINT'}}
function finish(){clearInterval(timer);timer=null;current=match.events.length;events=current;$('#phase').textContent='VERIFIED / A WINS';$('#runBtn').textContent='↻ RUN AGAIN';$('#progressBar').style.width='100%';updateScore(events);$('#outcome').textContent=`A WINS / 2—1 · ${matchScore.points.A} PTS`;$('#legality').textContent='24 / 24 LEGAL';$('#verifiedEvents').textContent='24 / 24';$('#replayDigest').textContent=match.digest.slice(0,4)+'·'+match.digest.slice(4,8)}
function reset(){setFrame(0);$('#seedLabel').textContent=String(seed).padStart(6,'0');$('#stateHash').textContent=match.digest.slice(0,4)+'·'+match.digest.slice(4,8);$('#outcome').textContent='—';$('#legality').textContent='—';$('#verifiedEvents').textContent='—';$('#replayDigest').textContent=match.digest.slice(0,4)+'·'+match.digest.slice(4,8)}
function run(){if(timer)return;$('#runBtn').textContent='Ⅱ PAUSE';$('#phase').textContent='LIVE';const pace=Number($('#speed').value);timer=setInterval(()=>{elapsed+=100;$('#clock').textContent=`00:${(elapsed/1000).toFixed(1).padStart(4,'0')}`;$('#progressBar').style.width=Math.min(100,(elapsed/108))+'%';if(elapsed>=current*450+450&&current<match.events.length)pushEvent(match.events[current]);if(current>=match.events.length)finish()},Math.max(55,180/pace))}
function toggleView(){viewMode=viewMode==='overview'?'decisive':'overview';$('#viewBtn').textContent=`VIEW: ${viewMode.toUpperCase()}`;updateLink(match.events[Math.max(0,current-1)])}
function exportTrace(){const payload=JSON.stringify(CyberRumbleEngine.trace(match,matchScore),null,2);const blob=new Blob([payload],{type:'application/json'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=`cyber-rumble-${match.seed}-${match.digest}.json`;link.click();URL.revokeObjectURL(url)}
$('#runBtn').addEventListener('click',()=>{if($('#phase').textContent.startsWith('VERIFIED')){reset();setTimeout(run,100)}else if(timer){clearInterval(timer);timer=null;$('#runBtn').textContent='▶ RESUME';$('#phase').textContent='PAUSED'}else run()});$('#resetBtn').addEventListener('click',reset);$('#viewBtn').addEventListener('click',toggleView);$('#exportBtn').addEventListener('click',exportTrace);$('#speed').addEventListener('input',e=>$('#speedLabel').textContent=e.target.value+'×');$('#scrubber').addEventListener('input',e=>setFrame(Number(e.target.value)));reset();
