const fs=require('fs'),crypto=require('crypto');
const manifest=JSON.parse(fs.readFileSync('manifest.json','utf8'));
const golden=JSON.parse(fs.readFileSync('golden-replay.json','utf8'));
const {buildMatch,scoreMatch}=require('./engine.js');
const replay=buildMatch(manifest.scenario.seed),score=scoreMatch(replay);
const files=['manifest.json','engine.js','sandbox.js',...manifest.artifacts];
const hashes=Object.fromEntries(files.map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex')]));
const publishedScore={winner:score.winner,points:score.points,categories:score.categories};
const result={schema:'cyber-rumble.portable-check.v1',benchmark_id:manifest.benchmark_id,version:manifest.version,seed:replay.seed,digest:replay.digest,event_count:replay.events.length,winners:replay.winners,score:publishedScore,environment:{node:process.version,platform:process.platform,arch:process.arch},artifact_sha256:hashes,comparison:{golden_digest_matches:replay.digest===golden.digest,golden_score_matches:JSON.stringify(publishedScore)===JSON.stringify(golden.score)}};
console.log(JSON.stringify(result,null,2));
if(!result.comparison.golden_digest_matches||!result.comparison.golden_score_matches)process.exitCode=1;
